// Generated standalone snapshot from kahustack-dsp commit 31595bef4a767d4852b5f44a6aaf8cafa84989c7.
// Do not edit this file as an independent validator. The canonical source remains
// apps/testbench/src/audio/LibraryManifestRuntime.ts in the parent kahustack-dsp repository.

import type {
  DspModuleManifest,
  DspParameterManifest,
  HostPortDirection,
  HostPortKind,
  HostPortManifest,
  HostPortRole,
  LibraryDomainManifest,
  LibraryManifest,
  ModuleId,
  ModuleKind,
  ModuleTarget,
  ModelNotesManifest,
  ParameterAutomation,
  ParameterControl,
  ParameterScale,
  ParameterTransition,
  RuntimeModuleManifest,
} from './types.js';

type UnknownRecord = Record<string, unknown>;

const GRID_EPSILON = 1e-9;

function isRecord(value: unknown): value is UnknownRecord {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function expectRecord(value: unknown, label: string): UnknownRecord {
  if (!isRecord(value)) throw new Error(`${label} must be an object.`);
  return value;
}

function expectString(value: unknown, label: string): string {
  if (typeof value !== 'string') throw new Error(`${label} must be a string.`);
  return value;
}

function expectFiniteNumber(value: unknown, label: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    throw new Error(`${label} must be a finite number.`);
  }
  return value;
}

function expectInteger(value: unknown, label: string): number {
  const numeric = expectFiniteNumber(value, label);
  if (!Number.isInteger(numeric)) throw new Error(`${label} must be an integer.`);
  return numeric;
}

function assertUnique<T extends string | number>(values: readonly T[], label: string): void {
  const seen = new Set<T>();
  for (const value of values) {
    if (seen.has(value)) throw new Error(`${label} contains duplicate value: ${value}.`);
    seen.add(value);
  }
}

function optionalString(record: UnknownRecord, key: string, label: string): string | undefined {
  const value = record[key];
  return value === undefined ? undefined : expectString(value, label);
}

function optionalFiniteNumber(record: UnknownRecord, key: string, label: string): number | undefined {
  const value = record[key];
  return value === undefined ? undefined : expectFiniteNumber(value, label);
}

function optionalInteger(record: UnknownRecord, key: string, label: string): number | undefined {
  const value = record[key];
  return value === undefined ? undefined : expectInteger(value, label);
}

function parseParameterControl(value: unknown, label: string): ParameterControl {
  switch (value) {
    case 'continuous':
    case 'enum':
    case 'boolean':
      return value;
    default:
      throw new Error(`${label} has unsupported control metadata.`);
  }
}

function parseParameterTransition(value: unknown, label: string): ParameterTransition {
  if (value === 'immediate' || value === 'reprepare') return value;
  if (typeof value === 'string') {
    const match = /^(linear-ramp|exponential|crossfade):([0-9]+(?:\.[0-9]+)?)ms$/.exec(value);
    const slew = /^slew-per-second:([0-9]+(?:\.[0-9]+)?)$/.exec(value);
    const amount = match?.[2] ?? slew?.[1];
    if (amount !== undefined && Number.isFinite(Number(amount)) && Number(amount) > 0) {
      return value as ParameterTransition;
    }
  }
  throw new Error(`${label} has unsupported transition metadata.`);
}

function parseParameterAutomation(value: unknown, label: string): ParameterAutomation {
  switch (value) {
    case 'realtime':
    case 'reprepare':
      return value;
    default:
      throw new Error(`${label} has unsupported automation metadata.`);
  }
}

function parseParameterScale(value: unknown, label: string): ParameterScale {
  switch (value) {
    case 'linear':
    case 'logarithmic':
    case 'decibels':
    case 'boolean':
    case 'enum':
      return value;
    default:
      throw new Error(`${label} has unsupported scale metadata.`);
  }
}

function parseModuleKind(value: unknown, label: string): ModuleKind {
  switch (value) {
    case 'primitive':
    case 'effect':
    case 'generator':
    case 'analyzer':
    case 'meter':
    case 'utility':
    case 'composite':
      return value;
    default:
      throw new Error(`${label} has unsupported module-kind metadata.`);
  }
}

function parseModuleTarget(value: unknown, label: string): ModuleTarget {
  switch (value) {
    case 'native':
    case 'wasm':
    case 'c-abi':
      return value;
    default:
      throw new Error(`${label} has unsupported target metadata.`);
  }
}

function parseHostPortKind(value: unknown, label: string): HostPortKind {
  switch (value) {
    case 'asset':
    case 'audio':
      return value;
    default:
      throw new Error(`${label} has unsupported host-port kind.`);
  }
}

function parseHostPortDirection(value: unknown, label: string): HostPortDirection {
  switch (value) {
    case 'input':
    case 'output':
      return value;
    default:
      throw new Error(`${label} has unsupported host-port direction.`);
  }
}

function parseHostPortRole(value: unknown, label: string): HostPortRole {
  switch (value) {
    case 'impulse-response':
    case 'auxiliary':
      return value;
    default:
      throw new Error(`${label} has unsupported host-port role.`);
  }
}

function parseStringArray(value: unknown, label: string): string[] {
  if (!Array.isArray(value)) throw new Error(`${label} must be an array.`);
  const values = value.map((entry, index) => expectString(entry, `${label}[${index}]`));
  if (values.length === 0 || values.some((entry) => entry.trim().length === 0)) {
    throw new Error(`${label} must contain non-empty strings.`);
  }
  return values;
}

function parseModelNotes(value: unknown, label: string): ModelNotesManifest {
  const record = expectRecord(value, label);
  const evidence = expectString(record['evidence'], `${label} evidence`);
  if (![
    'generic-model',
    'measured-specimen-fit',
    'datasheet-fit',
    'analytic-transfer',
  ].includes(evidence)) {
    throw new Error(`${label} evidence has unsupported class.`);
  }
  const tubeType = optionalString(record, 'tube_type', `${label} tube_type`);
  return {
    category: expectString(record['category'], `${label} category`),
    ...(tubeType === undefined ? {} : { tube_type: tubeType }),
    model_family: expectString(record['model_family'], `${label} model_family`),
    evidence: evidence as ModelNotesManifest['evidence'],
    reference: expectString(record['reference'], `${label} reference`),
    summary: expectString(record['summary'], `${label} summary`),
    behavior: parseStringArray(record['behavior'], `${label} behavior`),
    limitations: parseStringArray(record['limitations'], `${label} limitations`),
  };
}

function validateParameterValue(parameter: DspParameterManifest, value: number, label: string): void {
  if (!Number.isFinite(value)) throw new Error(`${label} must be finite.`);
  if (value < parameter.min || value > parameter.max) {
    throw new Error(`${label} = ${value} is outside [${parameter.min}, ${parameter.max}].`);
  }
}

function validateEnumValue(parameter: DspParameterManifest, value: number, label: string): void {
  if (parameter.control !== 'enum') return;
  if (!parameter.enum_values || parameter.enum_values.length === 0) {
    throw new Error(`${label} is missing enum labels.`);
  }
  if (!Number.isFinite(parameter.step) || parameter.step <= 0) {
    throw new Error(`${label} requires a positive enum step.`);
  }
  const span = (parameter.max - parameter.min) / parameter.step;
  const intervalCount = Math.round(span);
  if (Math.abs(span - intervalCount) > GRID_EPSILON) {
    throw new Error(`${label} has a min/max range that does not align to its enum step.`);
  }
  if (parameter.enum_values.length !== intervalCount + 1) {
    throw new Error(`${label} has ${parameter.enum_values.length} labels but its numeric grid requires ${intervalCount + 1}.`);
  }
  const offset = (value - parameter.min) / parameter.step;
  const index = Math.round(offset);
  if (Math.abs(offset - index) > GRID_EPSILON || index < 0 || index >= parameter.enum_values.length) {
    throw new Error(`${label} has invalid enum value ${value}.`);
  }
}

function parseDomain(value: unknown, index: number): LibraryDomainManifest {
  const record = expectRecord(value, `Generated library domain ${index}`);
  const description = optionalString(record, 'description', `Generated library domain ${index} description`);
  return {
    id: expectString(record['id'], `Generated library domain ${index} id`),
    name: expectString(record['name'], `Generated library domain ${index} name`),
    ...(description === undefined ? {} : { description }),
  };
}

function parseRuntime(value: unknown, moduleIndex: number): RuntimeModuleManifest {
  const record = expectRecord(value, `Generated module ${moduleIndex} runtime`);
  const registryIndex = expectInteger(record['registry_index'], `Generated module ${moduleIndex} runtime registry_index`);
  if (registryIndex < 0) {
    throw new Error(`Generated module ${moduleIndex} runtime registry_index must be non-negative.`);
  }
  const latencySamples = optionalInteger(record, 'latency_samples', `Generated module ${moduleIndex} runtime latency_samples`);
  if (latencySamples !== undefined && latencySamples < 0) {
    throw new Error(`Generated module ${moduleIndex} runtime latency_samples must be non-negative.`);
  }
  return {
    registry_index: registryIndex,
    ...(latencySamples === undefined ? {} : { latency_samples: latencySamples }),
  };
}

function parseParameter(value: unknown, moduleIndex: number, parameterIndex: number): DspParameterManifest {
  const label = `Generated parameter ${moduleIndex}:${parameterIndex}`;
  const record = expectRecord(value, label);
  const enumValuesValue = record['enum_values'];
  const enumValues = enumValuesValue === undefined ? undefined : parseStringArray(enumValuesValue, `${label} enum_values`);
  const displayMultiplier = optionalFiniteNumber(record, 'display_multiplier', `${label} display_multiplier`);
  const displayDecimals = optionalInteger(record, 'display_decimals', `${label} display_decimals`);
  const displayUnit = optionalString(record, 'display_unit', `${label} display_unit`);
  return {
    id: expectInteger(record['id'], `${label} id`),
    key: expectString(record['key'], `${label} key`),
    name: expectString(record['name'], `${label} name`),
    default: expectFiniteNumber(record['default'], `${label} default`),
    min: expectFiniteNumber(record['min'], `${label} min`),
    max: expectFiniteNumber(record['max'], `${label} max`),
    step: expectFiniteNumber(record['step'], `${label} step`),
    unit: expectString(record['unit'], `${label} unit`),
    scale: parseParameterScale(record['scale'], label),
    control: parseParameterControl(record['control'], label),
    transition: parseParameterTransition(record['transition'], label),
    automation: parseParameterAutomation(record['automation'], label),
    ...(enumValues === undefined ? {} : { enum_values: enumValues }),
    ...(displayMultiplier === undefined ? {} : { display_multiplier: displayMultiplier }),
    ...(displayDecimals === undefined ? {} : { display_decimals: displayDecimals }),
    ...(displayUnit === undefined ? {} : { display_unit: displayUnit }),
  };
}

function parseHostPort(value: unknown, moduleIndex: number, portIndex: number): HostPortManifest {
  const label = `Generated module ${moduleIndex} host port ${portIndex}`;
  const record = expectRecord(value, label);
  const roleValue = record['role'];
  const role = roleValue === undefined ? undefined : parseHostPortRole(roleValue, label);
  const index = optionalInteger(record, 'index', `${label} index`);
  return {
    id: expectString(record['id'], `${label} id`),
    name: expectString(record['name'], `${label} name`),
    kind: parseHostPortKind(record['kind'], label),
    direction: parseHostPortDirection(record['direction'], label),
    ...(role === undefined ? {} : { role }),
    ...(index === undefined ? {} : { index }),
  };
}

function parseModule(value: unknown, moduleIndex: number): DspModuleManifest {
  const label = `Generated module ${moduleIndex}`;
  const record = expectRecord(value, label);
  const idText = expectString(record['id'], `${label} id`);
  if (!isModuleId(idText)) {
    throw new Error(`${label} id must be a non-empty dotted module identifier.`);
  }
  const rawTargets = record['targets'];
  if (!Array.isArray(rawTargets)) throw new Error(`${label} targets must be an array.`);
  const targets = rawTargets.map((target, targetIndex) => parseModuleTarget(target, `${label} target ${targetIndex}`));
  const rawParameters = record['parameters'];
  if (!Array.isArray(rawParameters)) throw new Error(`${label} parameters must be an array.`);
  const parameters = rawParameters.map((parameter, parameterIndex) => parseParameter(parameter, moduleIndex, parameterIndex));
  assertUnique(parameters.map((parameter) => parameter.id), `${label} parameter ids`);
  assertUnique(parameters.map((parameter) => parameter.key), `${label} parameter keys`);
  for (const parameter of parameters) {
    if (parameter.step <= 0) {
      throw new Error(`${label} parameter ${parameter.key} requires a positive step.`);
    }
    const parameterLabel = `${label} parameter ${parameter.key}`;
    validateParameterValue(parameter, parameter.default, `${parameterLabel} default`);
    validateEnumValue(parameter, parameter.default, parameterLabel);
  }
  const rawHostPorts = record['host_ports'];
  const hostPorts = rawHostPorts === undefined ? undefined : (() => {
    if (!Array.isArray(rawHostPorts)) throw new Error(`${label} host_ports must be an array.`);
    return rawHostPorts.map((port, portIndex) => parseHostPort(port, moduleIndex, portIndex));
  })();
  if (hostPorts) assertUnique(hostPorts.map((port) => port.id), `${label} host port ids`);
  assertUnique(targets, `${label} targets`);
  const summary = optionalString(record, 'summary', `${label} summary`);
  const modelNotes = record['model_notes'] === undefined ? undefined : parseModelNotes(record['model_notes'], `${label} model_notes`);
  return {
    id: idText,
    name: expectString(record['name'], `${label} name`),
    domain: expectString(record['domain'], `${label} domain`),
    family: expectString(record['family'], `${label} family`),
    kind: parseModuleKind(record['kind'], label),
    maturity: expectString(record['maturity'], `${label} maturity`),
    version: expectString(record['version'], `${label} version`),
    ...(summary === undefined ? {} : { summary }),
    ...(modelNotes === undefined ? {} : { model_notes: modelNotes }),
    targets,
    parameters,
    ...(hostPorts === undefined ? {} : { host_ports: hostPorts }),
    runtime: parseRuntime(record['runtime'], moduleIndex),
  };
}

export function isModuleId(value: unknown): value is ModuleId {
  if (typeof value !== 'string') return false;
  const separator = value.indexOf('.');
  return separator > 0 && separator < value.length - 1;
}

export function resolveCatalogModuleId(catalog: LibraryManifest | null, value: string): ModuleId | null {
  if (!isModuleId(value)) return null;
  return catalog?.modules.some((module) => module.id === value) ? value : null;
}

export function parseLibraryManifest(value: unknown): LibraryManifest {
  const root = expectRecord(value, 'Generated library manifest');
  const schemaVersion = expectInteger(root['schemaVersion'], 'Generated library manifest schemaVersion');
  if (schemaVersion !== 1) {
    throw new Error(`Unsupported generated library manifest schemaVersion: ${schemaVersion}.`);
  }
  const library = expectRecord(root['library'], 'Generated library manifest library');
  const rawDomains = library['domains'];
  if (!Array.isArray(rawDomains)) throw new Error('Generated library manifest domains must be an array.');
  const domains = rawDomains.map(parseDomain);
  assertUnique(domains.map((domain) => domain.id), 'Generated library domain ids');
  const kinds = expectRecord(library['kinds'], 'Generated library manifest kinds');
  const rawKinds = kinds['allowed'];
  if (!Array.isArray(rawKinds)) throw new Error('Generated library manifest allowed kinds must be an array.');
  const allowedKinds = rawKinds.map((kind, index) => parseModuleKind(kind, `Generated library manifest allowed kind ${index}`));
  assertUnique(allowedKinds, 'Generated library allowed kinds');
  const rawModules = root['modules'];
  if (!Array.isArray(rawModules)) throw new Error('Generated library manifest modules must be an array.');
  const modules = rawModules.map(parseModule);
  assertUnique(modules.map((module) => module.id), 'Generated library module ids');
  const domainIds = new Set(domains.map((domain) => domain.id));
  const allowedKindSet = new Set(allowedKinds);
  for (const [moduleIndex, module] of modules.entries()) {
    if (!domainIds.has(module.domain)) {
      throw new Error(`Generated module ${module.id} references unknown domain: ${module.domain}.`);
    }
    if (!allowedKindSet.has(module.kind)) {
      throw new Error(`Generated module ${module.id} uses undeclared kind: ${module.kind}.`);
    }
    if (module.runtime.registry_index !== moduleIndex) {
      throw new Error(`Generated module ${module.id} registry_index ${module.runtime.registry_index} does not match catalog order ${moduleIndex}.`);
    }
  }
  const moduleCount = expectInteger(root['moduleCount'], 'Generated library manifest moduleCount');
  if (moduleCount !== modules.length) {
    throw new Error(`Generated library manifest moduleCount ${moduleCount} does not match modules length ${modules.length}.`);
  }
  return {
    schemaVersion: 1,
    library: {
      id: expectString(library['id'], 'Generated library id'),
      name: expectString(library['name'], 'Generated library name'),
      version: expectString(library['version'], 'Generated library version'),
      schema_version: expectInteger(library['schema_version'], 'Generated library schema_version'),
      manifest_format: expectInteger(library['manifest_format'], 'Generated library manifest_format'),
      domains,
      kinds: { allowed: allowedKinds },
    },
    moduleCount,
    modules,
  };
}
