// Generated standalone snapshot from kahustack-dsp commit 31595bef4a767d4852b5f44a6aaf8cafa84989c7.
// Do not edit this file as an independent schema. The canonical source remains apps/testbench/src/types.ts
// in the parent kahustack-dsp repository; stage-kahu-runtime.mjs prefers that source whenever available.

export type ModuleId = `${string}.${string}`;
export type ParameterKey = string;
export type ParameterId = number;

export type ParameterControl = 'continuous' | 'enum' | 'boolean';
export type ParameterTransition =
  | 'immediate'
  | 'reprepare'
  | `linear-ramp:${number}ms`
  | `exponential:${number}ms`
  | `slew-per-second:${number}`
  | `crossfade:${number}ms`;
export type ParameterAutomation = 'realtime' | 'reprepare';
export type ParameterScale = 'linear' | 'logarithmic' | 'decibels' | 'boolean' | 'enum';
export type ModuleKind =
  | 'primitive'
  | 'effect'
  | 'generator'
  | 'analyzer'
  | 'meter'
  | 'utility'
  | 'composite';
export type ModuleTarget = 'native' | 'wasm' | 'c-abi';
export type HostPortKind = 'asset' | 'audio';
export type HostPortDirection = 'input' | 'output';
export type HostPortRole = 'impulse-response' | 'auxiliary';

export interface DspParameterManifest {
  readonly id: ParameterId;
  readonly key: ParameterKey;
  readonly name: string;
  readonly default: number;
  readonly min: number;
  readonly max: number;
  readonly step: number;
  readonly unit: string;
  readonly scale: ParameterScale;
  readonly control: ParameterControl;
  readonly transition: ParameterTransition;
  readonly automation: ParameterAutomation;
  readonly enum_values?: readonly string[];
  readonly display_multiplier?: number;
  readonly display_decimals?: number;
  readonly display_unit?: string;
}

export interface HostPortManifest {
  readonly id: string;
  readonly name: string;
  readonly kind: HostPortKind;
  readonly direction: HostPortDirection;
  readonly role?: HostPortRole;
  readonly index?: number;
}

export type ModelEvidenceClass =
  | 'generic-model'
  | 'measured-specimen-fit'
  | 'datasheet-fit'
  | 'analytic-transfer';

export interface ModelNotesManifest {
  readonly category: string;
  readonly tube_type?: string;
  readonly model_family: string;
  readonly evidence: ModelEvidenceClass;
  readonly reference: string;
  readonly summary: string;
  readonly behavior: readonly string[];
  readonly limitations: readonly string[];
}

export interface RuntimeModuleManifest {
  readonly registry_index: number;
  readonly latency_samples?: number;
}

export interface DspModuleManifest {
  readonly id: ModuleId;
  readonly name: string;
  readonly domain: string;
  readonly family: string;
  readonly kind: ModuleKind;
  readonly maturity: string;
  readonly version: string;
  readonly summary?: string;
  readonly model_notes?: ModelNotesManifest;
  readonly targets: readonly ModuleTarget[];
  readonly parameters: readonly DspParameterManifest[];
  readonly host_ports?: readonly HostPortManifest[];
  readonly runtime: RuntimeModuleManifest;
}

export interface LibraryDomainManifest {
  id: string;
  name: string;
  description?: string;
}

export interface LibraryManifest {
  readonly schemaVersion: 1;
  library: {
    id: string;
    name: string;
    version: string;
    schema_version: number;
    manifest_format: number;
    domains: readonly LibraryDomainManifest[];
    kinds: {
      allowed: readonly ModuleKind[];
    };
  };
  moduleCount: number;
  modules: readonly DspModuleManifest[];
}
